version: '3.8'
services:
  gateway:
    build: gateway
    image: gateway_image
    container_name: shareit-gateway
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on: 
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8081

  server:
    build: server
    image: server_image
    container_name: shareit-server
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - db
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9091
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - DB_NAME=shareit
      - DB_HOST=db
      - DB_PORT=5432

  db:
    image: postgres:13.7-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name: shareit-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root